### ISSUE TITLE
Add the report to an output variable

### ISSUE THREAD

**Issue by lays147** [vladopajic/go-test-coverage#105]
Hi! I would like to request a feature of the report being published to the PR in a comment. It's easier to check on the PR without going to the action pipeline and seeing the output of this action. 

It could be nice to have this built-in on this action or have the full text in an output, so I can use it to add to the PR. 

Cheers!

**Comment by vladopajic** [comment]
hey @lays147, could you describe what kind of report are you interested to see?

--- 
please note that github action will currently mark errors on files in PR , when file is below set threshold. 

see [this PR](https://github.com/vladopajic/go-test-coverage/pull/106/files) as example. 
![image](https://github.com/user-attachments/assets/51a2e01e-e60b-47b9-8989-4f2c56f453ce)

**Comment by lays147** [comment]
@vladopajic This one:
![image](https://github.com/user-attachments/assets/1d00e05d-3c37-4c84-8c8c-f98a344a0c5d)

The annotations are a good thing, however having the summary on the PR is better than going on each file in the review (assuming that I'm the author of a PR)

Also, it would be another plus to have the lines that are not covered by the tests. So far I can only check this using `go tool cover -html`. It would be something similar to jest reports:
![image](https://github.com/user-attachments/assets/37a913e5-d753-4287-9a2d-cb3b3423e0ab)

**Comment by vladopajic** [comment]
hey,  [v2.10.3](https://github.com/vladopajic/go-test-coverage/releases/tag/v2.10.3) sets report to `report` variable.

please note since this is multi-line text it was escaped (according to [this post](https://github.com/orgs/community/discussions/26288)). it appears that github runner will automatically unescape in reverse, but if it is not happening then you'll need to do it manually. [this function](https://github.com/vladopajic/go-test-coverage/blob/main/pkg/testcoverage/report.go#L145) is used to format multi-line text.

please let me know if it works for you :)

----

uncovered lines might get added to reports later.

**Comment by vladopajic** [comment]
it makes sense, thanks for suggesting. :)

please try again [v2.10.4](https://github.com/vladopajic/go-test-coverage/releases/tag/v2.10.4) and let me know your impression

**Comment by vladopajic** [comment]
also added coverage reports to PRs in this repo:
https://github.com/vladopajic/go-test-coverage/pull/109#issuecomment-2466184163

**Comment by vladopajic** [comment]
@lays147 hey, iam kindly letting you know that this was implemented. once when check fails it will report all files that have missing coverage along with lines.

happy coding! 🌞

**Comment by lays147** [comment]
Thanks for the update @vladopajic! Great work!

**Comment by lays147** [comment]
@vladopajic I was checking the docs, and would suggest you to use [this action for the PR Report Comment](https://github.com/thollander/actions-comment-pull-request). Thollander action already knows how to manage it, and you don't need to do the manual steps on the [presented here](https://github.com/vladopajic/go-test-coverage/blob/main/docs/github_action.md#post-coverage-report-to-pr).

**Comment by vladopajic** [comment]
good suggestion, thanks for letting me know

**Comment by lays147** [comment]
Here's an example:
```yaml
      - name: check test coverage
        id: coverage
        if: always()
        uses: vladopajic/go-test-coverage@v2
        continue-on-error: true
        with:
          config: ./.testcoverage.yaml

      - name: Comment Coverage on PR
        if: always()
        uses: thollander/actions-comment-pull-request@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_tag: coverage-report
          message: |
            ### Coverage Report
            > Para mais detalhes de como a cobertura é configurada, veja o arquivo `.testcoverage.yaml`
            <detail>
            ``` ${{ fromJSON(steps.coverage.outputs.report) }} ```
            </detail>
```
