### ISSUE TITLE
feat: post comments using action

### ISSUE THREAD

**Issue by vladopajic** [vladopajic/go-test-coverage#182]
currently `go-test-coverage` doesn't post comments on github PRs. this functionality is implemented using other actions (as explained [here](https://github.com/vladopajic/go-test-coverage/blob/main/docs/github_action.md#post-coverage-report-to-pr)). 

this issue tracks effort to implement posting comments on github PRs using this action.

for example when `comment-report: true` input is used github action can post/update comment with report directly on PR without need for other actions.

code example:
```yml
 - name: check test coverage
    uses: vladopajic/go-test-coverage@v2
    with:
      config: ./.github/.testcoverage.yml
      profile: ubuntu-latest-profile,macos-latest-profile,windows-latest-profile
      comment-report: true
```
