### ISSUE TITLE
Override order issue

### ISSUE THREAD

**Issue by stuart-clark-exeter** [vladopajic/go-test-coverage#23]
If I have my config like this:

```
override:
  - threshold: 90
    path: ^x/.+/keeper(/|$)
  - threshold: 80
    path: ^x/organization/keeper/identity\.go
```

Then x/organization/keeper/identity.go is still held to 90% coverage

There is a work around, this works as expected:

```
override:
  - threshold: 80
    path: ^x/organization/keeper/identity\.go
  - threshold: 90
    path: ^x/.+/keeper(/|$)
```

So I think either this needs to be documented, or better yet the more "precise" regex is favoured when selecting thresholds.

Thanks again for all the effort that has / is being put into this library I'm very grateful!
